server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/frontline/downloads;
    autoindex on;

    location / {
        try_files $uri $uri/ =404;
    }

    location /downloads/ {
        alias /var/frontline/downloads/;
        autoindex on;
        add_header Content-Disposition 'attachment' always;
    }

    # pagina simples
    location = / {
        return 302 /index.html;
    }
}
